#ifndef CONFIG_H
#define CONFIG_H

#define FLAME_DESCRIPTOR_TABLE 512

#define KERNEL_CODE_SEG 0x08
#define KERNEL_DATA_SEG 0x10

#define FLAMEOS_HEAP_SIZE_BYTES 104857600
#define FLMAEOS_HEAP_BLOCK_SIZE 4096
#define FLAMEOS_HEAP_ADDRESS 0x01000000 
#define FLMAEOS_HEAP_TABLE_ADDRESS 0x00007E00

#define FLAMEOS_SECTOR_SIZE 512

#define FLAMEOS_MAX_FILE_SYSTEM 12
#define FLAMEOS_MAX_FILE_DESCRIPTORS 512

#define FLAMEOS_MAX_FILE_LENGTH 108

#define FLAMEOS_TOTAL_GDT_SEGMENTS 6

#define FLAMEOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define FLAMEOS_PROGRAM_STACK_SIZE 1024*16
#define FLAMEOS_PROGRAM_STACK_ADDRESS_START 0x3FF000
#define FLAMEOS_PROGRAM_STACK_ADDRESS_END FLAMEOS_PROGRAM_STACK_ADDRESS_START - FLAMEOS_PROGRAM_STACK_SIZE

#define FLAMEOS_USER_CODE_SEG 0x23
#define FLAMEOS_USER_DATA_SEG 0x1B

#define FLAMEOS_MAX_PROGRAMS 1024
#define FLAMEOS_MAX_PROCESS 12
#endif
